config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :users, only: %i[index]
  resources :relationships, only: %i[create destroy], module: :users
  resources :posts, only: %i[index new create show edit update destroy]
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :content, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, presence: true

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationship = current_user.active_relationships.find_by(followed_id: user.id)
    relationship.destroy!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update]
  before_action :authenticate_user!, only: %i[new create edit update]
  before_action :correct_user, only: %i[edit update]

  def index
    @posts = Post.order(id: :desc).limit(10)
  end

  def new
    @post = Post.new
  end

  def show
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path, notice: '投稿作成！'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @post.destroy!
    redirect_to root_path, notice: '削除完了'
    end
  private

  def correct_user
    @user = User.find(@post.user_id)
    redirect_to(root_url, status: :see_other) unless @user == current_user
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]

  def create
    user = User.find(params[:user_id])
    if current_user.follow(user)
      redirect_to users_path, notice: 'フォローしました'
    else
      redirect_to users_path, alert: 'フォロー失敗'
    end
  end

  def destroy
    relationship = current_user.active_relationships.find(params[:id])
    relationship.destroy!
    redirect_to users_path, notice: 'フォロー解除しました'
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/relationships_controller.rb
class Users::RelationshipsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]

  def create
    user = User.find(params[:user_id])
    if current_user.follow(user)
      redirect_to users_path, notice: 'フォローしました'
    else
      redirect_to users_path, alert: 'フォロー失敗'
    end
  end

  def destroy
    relationship = current_user.active_relationships.find(params[:id])
    relationship.destroy!
    redirect_to users_path, notice: 'フォロー解除しました'
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[index]
  def index
    @users = User.order(id: :desc).limit(10)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.haml
- if user_signed_in?
  email: 
  = current_user.email 
- else
  = link_to("ログイン",new_user_session_path)
  = link_to("新規登録",new_user_registration_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || "Miniblog"
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    %meta{:content => "yes", :name => "mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{:href => "/icon.png", :rel => "icon", :type => "image/png"}/
    %link{:href => "/icon.svg", :rel => "icon", :type => "image/svg+xml"}/
    %link{:href => "/icon.png", :rel => "apple-touch-icon"}/
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"
  %body
    = render 'layouts/header' 
    .container
      = yield

app/views/posts/_form.html.haml
= simple_form_for post do |f|
  = f.input :content
  = f.button :submit, class: 'btn btn-primary'

app/views/posts/edit.html.haml
= render 'form', post: @post

app/views/posts/index.html.haml
- if flash[:notice]
  .alert.alert-success= notice
%ul.list-group
  - @posts.each do |post|
    - @user = post.user 
    %li.list-group-item
      = post.content
      = @user.email
      = link_to '編集', edit_post_path(post)
      = link_to '詳細', post_path(post)
      = link_to '削除', post_path(post), data: { turbo_method: :delete, turbo_confirm: "削除します、よろしいですか？" }
= link_to '新規投稿', new_post_path

app/views/posts/new.html.haml
= render 'form', post: @post

app/views/posts/show.html.haml
- @user = @post.user
%container 
  = @post.content
  = @user.email
  = @post.created_at
= link_to("ポスト一覧",posts_path)

app/views/users/index.html.haml
- if flash[:notice]
  .alert.alert-success= notice
%h1 ユーザー一覧
%ul.list-group
  - @users.each do |user|
    %li.list-group-item
      = user.email
      - relationship = current_user.active_relationships.find_by(followed_id: user.id)
      - if relationship
        = button_to 'フォロー解除', relationship_path(relationship), method: :delete
      - else
        = button_to 'フォロー', relationships_path, method: :post , params: {user_id:user.id}

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>